module.exports = {
   modules: {
      'Getting Started': [
         'welcome',
      ],
      'Hardware Interfaces': [
         // 	// 'hardware/gpio',
         // 	// 'hardware/pwm',
         // 	// 'hardware/uart',
         // 	// 'hardware/usb',
         // 	// 'hardware/nfc',
         'hardware/dxBarcode',
         'hardware/dxCode',
         'hardware/dxOs',
         // 	// 'hardware/bluetooth',
         'hardware/dxAudio',
         'hardware/dxAlsa',
         'hardware/dxAlsaplay',
         'hardware/dxPwm',
         'hardware/dxNfc',
         'hardware/dxNfcCard',
         // 	// 'hardware/watchdog',
      ],
      'Network & Communication': [
         'network/dxNetwork',
         'network/dxHttpServer',
         'network/dxHttpClient',
         'network/dxMqttClient',
         'network/dxNet',
         'network/dxWebserver',
         'network/dxHttp',
         'network/dxMqtt',
      ],
      'DB': [
         'db/dxSqlite',
         'db/dxSqliteDB',
         'db/dxKeyValueDB',
      ],
      'UI': [
         'ui/dxUi',
      ],
      // 'GUI Development': [
      // 	// 'gui/components',
      // 	// 'gui/layouts',
      // 	// 'gui/events',
      // 	// 'gui/threading',
      // ],
      'System & Utilities': [
         'utils/dxLogger',
         'utils/dxNtp',
         'utils/dxTimeZones',
         'utils/dxIconv',
         'utils/dxOta',
         'utils/dxStd',
         'utils/dxCommonUtils',
         'utils/dxCryptoES',
         'utils/dxEventBus',
         'utils/dxConfiguration',
         'utils/dxConfig',
         'utils/dxMap',
         'utils/dxQueue',
         'utils/dxWorkerPool'

         // 	// 'utils/encryption',
         // 	// 'utils/logging',
         // 	// 'utils/ntp',
         // 	// 'utils/sqlite',
      ],
   },
}; 