module.exports = {
	docs: {
		'Getting Started': [
			'welcome',
			'basics/installation',
			'basics/quick-start',
			'basics/dejaos-device'
		],
		 'Core Concepts': [
			'basics/dejaos-arch',
			'basics/javascript-engine',
		 	'basics/gui-engine',
			'basics/modules',
		 	'basics/ide',
			'basics/project',
			'basics/debugging',
			'basics/app',
			'basics/mode',
		 ],
		// 'Hardware Interfaces': [
		// 	// 'hardware/gpio',
		// 	// 'hardware/pwm',
		// 	// 'hardware/uart',
		// 	// 'hardware/usb',
		// 	// 'hardware/nfc',
		// 	// 'hardware/qrcode',
		// 	// 'hardware/bluetooth',
		// 	// 'hardware/audio',
		// 	// 'hardware/watchdog',
		// ],
		// 'Network & Communication': [
		// 	// 'network/tcp',
		// 	// 'network/udp',
		// 	// 'network/http',
		// 	// 'network/mqtt',
		// 	// 'network/webserver',
		// 	// 'network/osdp',
		// ],
		// 'GUI Development': [
		// 	// 'gui/basics',
		// 	// 'gui/components',
		// 	// 'gui/layouts',
		// 	// 'gui/events',
		// 	// 'gui/threading',
		// ],
		// 'System & Utilities': [
		// 	// 'utils/threads',
		// 	// 'utils/eventbus',
		// 	// 'utils/encryption',
		// 	// 'utils/logging',
		// 	// 'utils/ntp',
		// 	// 'utils/sqlite',
		// ],
		// 'Development Tools': [
		// 	// 'tools/packaging',
		// 	// 'tools/deployment',
		// 	// 'tools/updates',
		// 	// 'tools/third-party',
		// ],
		// Tutorials: [
		// 	// 'tutorials/led-control',
		// 	// 'tutorials/touch-screen',
		// 	// 'tutorials/network-app',
		// 	// 'tutorials/database-app',
		// ],
		// 'API Reference': [
		// 	// 'api/hardware',
		// 	// 'api/network',
		// 	// 'api/gui',
		// 	// 'api/utils',
		// ],
	},
	// hardware: {
	// 	'Hardware Interfaces': [
	// 		'welcome',
	// 		'gpio',
	// 		'pwm',
	// 		'uart',
	// 		'usb',
	// 		'nfc',
	// 		'qrcode',
	// 		'bluetooth',
	// 		'audio',
	// 		'watchdog',
	// 	],
	// },
	// gui: {
	// 	'GUI Development': [
	// 		'welcome',
	// 		'basics',
	// 		'components',
	// 		'layouts',
	// 		'events',
	// 		'threading',
	// 	],
	// },
};
